<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Deliveryschedule
 * @version     0.1.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
<?php /** @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available */ ?>
<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php if (!$_shippingRateGroups): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
    <?php else: ?>

    <dl class="sp-methods">
        <?php $shippingCodePrice = array(); ?>
        <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
            <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
            <dd>
                <ul>
                    <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                        <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                        <li>
                            <?php if ($_rate->getErrorMessage()): ?>
                                <ul class="messages"><li class="error-msg"><ul><li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li></ul></li></ul>
                                <?php else: ?>
                                <?php if ($_sole) : ?>
                                    <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                                    <?php else: ?>
                                    <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()){ echo ' checked="checked"'; } ?> class="radio"/>

                                <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                    <script type="text/javascript">
                                        //<![CDATA[
                                        lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                        //]]>
                                    </script>
                                    <?php endif; ?>

                            <?php endif; ?>
                        <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                            <?php echo $_excl; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                        </label>
                        <?php endif ?>
                    </li>
                    <?php endforeach; ?>
            </ul>
        </dd>
        <?php endforeach; ?>
    <?php 
        if (Mage::getStoreConfig('deliveryschedule/general/delivery_schedule_enabled')==1){
            echo $this->getLayout()->createBlock('deliveryschedule/deliveryschedule')->setTemplate('deliveryschedule/deliveryschedule.phtml')->toHtml(); 
        }
    ?>
</dl>
<script type="text/javascript">
    //<![CDATA[
    <?php if (!empty($shippingCodePrice)): ?>
        var shippingCodePrice = {<?php echo implode(',',$shippingCodePrice); ?>};
        <?php endif; ?>

    $$('input[type="radio"][name="shipping_method"]').each(function(el){
            Event.observe(el, 'click', function(){
                    if (el.checked == true) {
                        var getShippingCode = el.getValue();
                        <?php if (!empty($shippingCodePrice)): ?>
                            var newPrice = shippingCodePrice[getShippingCode];
                            if (!lastPrice) {
                                lastPrice = newPrice;
                                quoteBaseGrandTotal += newPrice;
                            }
                            if (newPrice != lastPrice) {
                                quoteBaseGrandTotal += (newPrice-lastPrice);
                                lastPrice = newPrice;
                            }
                            <?php endif; ?>
                        checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
                        return false;
                    }
            });
    });
    //]]>
</script>
<?php endif; ?>
