<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Deliveryschedule
 * @version     0.1.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
<?php /** @var $this Mage_Adminhtml_Block_Sales_Order_View_Tab_Info */ ?>
<?php $_order = $this->getOrder() ?>
<div>
<div id="order-messages">
    <?php echo $this->getChildHtml('order_messages') ?>
</div>
<?php echo $this->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?php echo $_order->getId() ?>"/>
<?php if ($_order->getIsVirtual()): ?>
    <div class="box-right">
        <?php else: ?>
        <div class="box-left">
            <?php endif; ?>
        <!--Payment Method-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Information') ?></h4>
            </div>
            <fieldset>
                <?php echo $this->getPaymentHtml() ?>
                <div><?php echo Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
            </fieldset>
        </div>
    </div>
    <?php if (!$_order->getIsVirtual()): ?>
        <div class="box-right">
            <!--Shipping Method-->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping &amp; Handling Information') ?></h4>
                </div>
                <fieldset>
                    <?php  if ($_order->getTracksCollection()->count()) : ?>
                        <a href="#" id="linkId" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php echo $this->__('Track Order') ?>"><?php echo $this->__('Track Order') ?></a>
                        <br/>
                        <?php endif; ?>
                    <?php if ($_order->getShippingDescription()): ?>
                        <strong><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></strong>

                        <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                            <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                            <?php else: ?>
                            <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                            <?php endif; ?>
                        <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                        <?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                        <?php else: ?>
                        <?php echo $this->helper('sales')->__('No shipping information available'); ?>
                        <?php endif; ?>
                </fieldset>
            </div>
        </div>
        <?php endif; ?>
        <div class="clear"></div>
        <?php 
        $checkInfo = $_order->getShippingDeliverySchedule();
        if($checkInfo && $checkInfo != "") { ?>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-products"><?php echo Mage::helper('deliveryschedule')->__('Delivery Schedule Information') ?></h4>
            </div>
        </div>
        <div class="grid np">
            <fieldset>
                <?php  
                    $getDeliveryDate = $_order->getShippingDeliveryDate();
                    $getDeliveryType = $_order->getShippingDeliverySchedule();
                    $getDeliveryTime = $_order->getShippingDeliveryTime();
                    echo "<strong>".$this->__('Shipping Delivery Schedule')." :- </strong></br>".$getDeliveryType;
                    if ($getDeliveryDate!='') {
                        echo "</br><strong>".$this->__('Shipping Delivery Date')." :- </strong></br>".date("M d Y",strtotime($getDeliveryDate))." ".$getDeliveryTime;
                   }
                    else {
                        echo "<strong>".$this->__('Shipping Delivery Schedule')." :- </strong> N/A";
                        }
                    if (Mage::getStoreConfig ( 'deliveryschedule/general/delivery_comment_enabled' ) == 1) {
                       $getComments = $_order->getShippingDeliveryComments();
                    if ($getComments!=''){
                        echo "<br/><strong>".$this->__('Comments')." :- </strong>".$getComments;
                        }
                    else {
                        echo "</br><strong>".$this->__('Comments')." :- </strong> N/A";
                        }
                    }
                ?>
            </fieldset>
        </div>
        <?php } ?>
    <?php echo $this->getGiftOptionsHtml() ?>
    <div class="clear"></div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items Ordered') ?></h4>
        </div>
    </div>
    <?php echo $this->getItemsHtml() ?>
    <div class="clear"></div>

    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?php echo Mage::helper('sales')->__('Comments History') ?></h4>
            </div>
            <fieldset><?php echo $this->getChildHtml('order_history') ?></fieldset>
        </div>
    </div>
    <div class="box-right entry-edit">
        <div class="entry-edit-head"><h4><?php echo Mage::helper('sales')->__('Order Totals') ?></h4></div>
        <div class="order-totals"><?php echo $this->getChildHtml('order_totals') ?></div>
    </div>
    <div class="clear"></div>
</div>

<?php echo $this->getChildHtml('popup_window');?>
<script type="text/javascript">
    //<![CDATA[
    /**
    * Retrieve gift options tooltip content
    */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
                if (element.down(0)) {
                    headerLine = element.down(0).innerHTML;
                    contentLine = element.down(0).next().innerHTML;
                    if (contentLine.length > 30) {
                        contentLine = contentLine.slice(0,30) + '...';
                    }
                    contentLines.push(headerLine + ' ' + contentLine);
                }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
    //]]>
</script>
