<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Deliveryschedule
 * @version     0.1.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
<?php $_order = $this->getOrder() ?>
<h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<div class="col2-set">
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="col-1">
        <h2><?php echo $this->__('Shipping Address') ?></h2>
        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
    </div>
    <div class="col-2">
    <?php else: ?>
    <div class="col-1">
    <?php endif; ?>
        <h2><?php echo $this->__('Billing Address') ?></h2>
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </div>
<?php if (!$_order->getIsVirtual()): ?>
</div>
<div class="col2-set">
    <div class="col-1">
        <h2><?php echo $this->__('Shipping Method') ?></h2>
         <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
    </div>
<?php endif; ?>
    <div class="col-2">
        <h2><?php echo $this->__('Payment Method') ?></h2>
        <?php echo $this->getPaymentInfoHtml() ?>
    </div>
</div>
<?php 
$checkEmpty = $_order->getShippingDeliverySchedule();
if($checkEmpty && $checkEmpty != "") { ?>
<div class="col2-set">
        <h2><?php echo $this->__('Delivery Schedule Information') ?></h2>
        <div class="col-1">
         <?php 
         /**
          * Display shipping delivery schedule information
          */
                    $deliveryDates = $_order->getShippingDeliveryDate();
                    $deliveryTypes = $_order->getShippingDeliverySchedule();
                    $deliveryTimes = $_order->getShippingDeliveryTime();
                    echo "<strong>".$this->__('Shipping Delivery Schedule')." :- </strong></br>".$_order->getShippingDeliverySchedule();
                    if ($_order->getShippingDeliveryDate()!='') {
                        echo "</br><strong>".$this->__('Shipping Delivery Date')." :- </strong></br>".date("M d Y",strtotime($deliveryDates))." ".$deliveryTimes;
                    }
                    else {
                        echo "<strong>".$this->__('Shipping Delivery Schedule')." :- </strong> N/A";
                        }
                    ?></div><div class="col-2"><?php 
                    if (Mage::getStoreConfig ( 'deliveryschedule/general/delivery_comment_enabled' ) == 1) {
                    if ($_order->getShippingDeliveryComments()!='') {
                        echo "<strong>".$this->__('Comments')." :- </strong></br>".$_order->getShippingDeliveryComments();
                        }
                    else {
                        echo "<strong>".$this->__('Comments')." :- </strong> N/A";
                        }
                    }
                ?>
                </div>
</div>
<?php } ?>
<h2><?php echo $this->__('Items Ordered') ?></h2>
<table class="data-table" id="my-orders-table">
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th><?php echo $this->__('SKU') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tfoot>
        <?php echo $this->getChildHtml('order_totals') ?>
    </tfoot>
    <?php $_items = $_order->getItemsCollection(); ?>
    <?php $_count = $_items->count(); ?>
    <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getParentItem()) {
        continue; 
    }?>
    <tbody>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
        <?php endforeach; ?>
</table>
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<script type="text/javascript">window.print();</script>
