<?php 

$_product = Mage::registry('current_product');
//$attributeValue = Mage::getModel('catalog/product')->load($_product->getId())->getAttributeInsalled();
$attributeValue = $_product->getData('owner_id');
//$_product->getResource()->getAttribute('attribute_insalled')->getFrontend()->getValue($_product);
if ($attributeValue) {
  			$output = '<ul><li>';
        	$output .= $attributeValue;
        	$output .= '</li></ul>';
        	echo $output;
  		}
?>
